### ISSUE TITLE
Unable to convert json from DB facade result

### ISSUE THREAD

**Issue by ericlie** [grohiro/laravel-camelcase-json#2]
Hi there,

Really love this package. However I am facing an issue where there is a condition that force me to use Laravel's DB facade instead of Eloquent Model. Please refer to following code:

```php
$users = DB::table('users')->select('name AS some_cool_name')->get()
return response()->json($users);
```
The result shows "**some_cool_name**" instead of "**someCoolName**"
I am using Laravel 5.4

**Comment by anil1712** [comment]
Yeah, I am also getting the same.
